# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4b95e5e351d2091a31dd30c3348c4a6"
name = "commercial-duplication-app"
application_url = "https://soap-smilies-yesterday-routine.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testshoprestapi.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://soap-smilies-yesterday-routine.trycloudflare.com/auth/callback",
  "https://soap-smilies-yesterday-routine.trycloudflare.com/auth/shopify/callback",
  "https://soap-smilies-yesterday-routine.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
